checkbox
js-tasks-ru/htmlcss-20240216_vladimir-khleborodov pull request #18
Opened 2024-03-25 17:09 UTC by VladimirKhleborodov

2024-03-25 17:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-01 17:48 UTC, GSemikozov requested changes

2024-04-01 17:48 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  stroke: var(--white);
проще ведь через color и не использовать все эти stroke)

2024-04-08 14:23 UTC, GSemikozov approved these changes

2024-04-08 14:23 UTC, merged