radio
js-tasks-ru/htmlcss-20240216_vladimir-khleborodov pull request #19
Opened 2024-03-27 10:11 UTC by VladimirKhleborodov

2024-03-27 10:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-03 19:59 UTC, GSemikozov requested changes

2024-04-03 19:59 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +          <svg class="radio__icon-inner">
а вот это уже лишнее, простой кружок можно отрисовать и через css)

2024-04-08 14:24 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +          <svg class="radio__icon-inner">
все еще атуально (свг не надо)

2024-04-08 14:24 UTC, GSemikozov requested changes
конфликт

2024-04-09 14:06 UTC, GSemikozov requested changes

2024-04-09 14:06 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +          <div class="radio__circle-outer"></div>
нам достаточно одного элемента radio__circle, просто меняем его отрисовку при radio__button:checked

2024-04-09 14:06 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +          <div class="radio__circle-outer"></div>
показать / скрыть

2024-04-14 11:28 UTC, GSemikozov approved these changes

2024-04-14 11:28 UTC, merged