mobile page of index.html
js-tasks-ru/htmlcss-20240216_vladimir-khleborodov pull request #23
Opened 2024-03-28 16:24 UTC by VladimirKhleborodov

Сделана адаптивная верстка главной страницы index.html.

2024-03-28 16:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-03 10:29 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-03 20:11 UTC, GSemikozov requested changes

2024-04-03 20:11 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip_preview {
ой, а это все зачем? просто показываем тултип и все (.tooltip__bubble { display: block })

2024-04-04 09:41 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-04 10:01 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-04 11:54 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-04 13:05 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-08 14:26 UTC, GSemikozov requested changes

2024-04-08 14:26 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip_preview {
все еще актуально

2024-04-08 15:08 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-04-08 15:12 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-08 15:24 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-10 10:10 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-10 10:55 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-10 13:25 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-15 10:28 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-23 21:28 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-26 12:26 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-29 10:53 UTC, GSemikozov approved these changes

2024-04-29 10:53 UTC, merged